# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c429903037f507aa6dec536c41048c723df8bfdb6904ab23bc03c578b1eb59d4d715f35e9c33e6b0099e7c758b61170d7ea7577d515ff29578b01eb320006c

test:
  secret_key_base: f10905ffcb3a43f7469ae6824a492db6cc46d5f7a15824c9a02abbdec804aa0f052d064cfc0199ab5b856328e1135e21968ca20dd8e1cde4d6a57c8d0241a4f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
