# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbff288e935f64fa412ec5b0184bf255d27b60065b63c72183dfe281c414ce825beaa1e8c0afe9340e9825c1d411076157fe32fbadb4f8dd196d8fbb5be3604e

test:
  secret_key_base: 212fae51cfad8be493c53019bca05ec3ac8743f3a6c1c2ec3ab2df3780dfeca801e1888d4983bd0b7f2b2a44875d0747f22e181ce81a90c33d6790cb6971f87c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
